### ISSUE TITLE
virtual-service-type-vs

### ISSUE THREAD

**Issue by arharrison** [HL7Norway/NoBasisAppointment#1]
Profiler ser bra ut men jeg kunne ikke finner noe referanse til urn:oid:2.16.840.1.113883.4.642.4.1809 fra  https://hl7norway.github.io/NoBasisAppointment/output/ValueSet-no-basis-virtual-service-type-vs.html

Skal dette bli en Volven alternativ til HL/ terminologien?

Mvh, Andy

**Comment by rockphotog** [comment]
Nei, jeg måtte søke litt på nett. 

Bør kanskje identifiseres med
`http://hl7.org/fhir/virtual-service-type` ( https://hl7.org/fhir/codesystem-virtual-service-type.html )

i stedet for ".1809" da URI vel er preferert over OID.

**Comment by thomiz** [comment]
Enig, var det noen grunn til å bruke oid for virtual-service-type her @helgaarm ?

Fikk svar fra Arman og det var et problem med valideringen når det benyttes et R5 kodeverk i R4 extension definisjon. Det fungerer med oid, for da sjekker ikke validatoren mot det faktiske kodeverket. 

Det er likevel et åpent spørsmål om hva som skjer i faktiske implementasjoner når man forsøker å benytte dette kodeverket og validere mot det.

**Comment by thomiz** [comment]
Vi tar ikke dette verdisettet inn som en del av no-basis. Hvis vi oppretter en R4 versjon av dette blir det HL7 Norge sitt verdisett som vi må forvalte og ikke en ren kopi av HL7 internasjonalt sin. Dette er et forvaltningsansvar vi ikke ønsker.

**De som skal implementere dette må hente en kopi av verdisettet for bruk i implementasjonen.**
